theme = 'catppuccin_mocha'

[editor]
line-number = 'relative'
mouse = true
gutters = ["diagnostics", "line-numbers"]
idle-timeout = 0
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections","file-type","file-encoding","file-line-ending","position","position-percentage"]

[editor.cursor-shape]
insert = 'underline'
